# Generated by Django 5.2.11 on 2026-09-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blueflow", "0012_remove_externalsystem_ip_address"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="assetcustomfield",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="assetcustomfield",
            name="value_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="historicalassetcustomfield",
            name="value_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddConstraint(
            model_name="assetcustomfield",
            constraint=models.UniqueConstraint(
                fields=("asset", "field"), name="unique_asset_field"
            ),
        ),
    ]
